---
- hosts: kubernetes
  user: root

  tasks:
    - name: deploy myP1 on kubernetes
      command: kubectl apply -f /root/myp1-deployment.yml

    - name: create service for myP1 deployment
      command: kubectl apply -f /root/myp1-service.yaml

    - name: update deployment with new pods if image updated in docker hub
      command: kubectl rollout restart deployment.apps/myp1-deployment
