apiVersion: apps/v1
kind: Deployment
metadata:
  name: myp1-deployment
  labels:
    app: myp1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myp1
  template:
    metadata:
      labels:
        app: myp1
    spec:
      containers:
      - name: myp1
        image: myimagera:latest
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
